import crypto from "node:crypto";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/server/auth/permissions";
import { withActorTransaction } from "@/server/db";
import { ApiError, assertSameOrigin, fail, ok, parseBody } from "@/server/http";
import { normalizeCustomerEmail, normalizeCustomerPhone } from "@/features/customer-management/schemas";

const input = z.object({ name: z.string().trim().min(2).max(160), phone: z.string().trim().min(5).max(40).optional(), email: z.email().optional(), address: z.string().max(1000).optional(), notes: z.string().max(4000).optional() }).refine((value) => value.phone || value.email, "Telepon atau email wajib diisi");

export async function GET(request: NextRequest) { try { const requestId=crypto.randomUUID(); const user=await requirePermission(request,requestId,"service.read"); const query=(request.nextUrl.searchParams.get("query")||"").trim(); const limit=Math.min(Math.max(Number(request.nextUrl.searchParams.get("limit")||100),1),200); const offset=Math.max(Number(request.nextUrl.searchParams.get("offset")||0),0); const data=await withActorTransaction({userId:user.id,role:user.role,requestId},async(c)=>(await c.query(`SELECT id,name,phone,email,address,notes,is_active AS "isActive",created_at AS "createdAt" FROM app.customers WHERE merged_into_id IS NULL AND ($1='' OR name ILIKE '%'||$1||'%' OR phone ILIKE '%'||$1||'%' OR email ILIKE '%'||$1||'%') ORDER BY updated_at DESC,id LIMIT $2 OFFSET $3`,[query,limit,offset])).rows); return ok(data,{requestId,limit,offset}); } catch(error){return fail(error);} }
export async function POST(request: NextRequest) { try { assertSameOrigin(request); const requestId=crypto.randomUUID(); const user=await requirePermission(request,requestId,"service.create"); const body=await parseBody(request,input); const normalizedPhone=normalizeCustomerPhone(body.phone); const normalizedEmail=normalizeCustomerEmail(body.email); const data=await withActorTransaction({userId:user.id,role:user.role,requestId},async(c)=>{try{return (await c.query("INSERT INTO app.customers(name,phone,email,address,notes,normalized_phone,normalized_email,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING id,name,phone,email",[body.name,body.phone||null,body.email||null,body.address||null,body.notes||null,normalizedPhone,normalizedEmail,user.id])).rows[0];}catch(error){if(error&&typeof error==='object'&&'code' in error&&error.code==='23505')throw new ApiError(409,"CUSTOMER_CONTACT_EXISTS","Nomor telepon atau email sudah dipakai pelanggan lain");throw error;}}); return ok(data,{requestId}); }catch(error){return fail(error);} }
