import crypto from "node:crypto";
import { NextRequest } from "next/server";
import { z } from "zod";
import { recordAudit } from "@/server/audit";
import { requirePermission } from "@/server/auth/permissions";
import { withActorTransaction } from "@/server/db";
import { ApiError, assertSameOrigin, fail, ok, parseBody } from "@/server/http";

const input = z.object({ rating: z.coerce.number().int().min(1).max(5), comments: z.string().trim().max(2000).nullable().optional() });
export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { const requestId=crypto.randomUUID(); const user=await requirePermission(request,requestId,"service.read"); const id=z.uuid().parse((await context.params).id); const data=await withActorTransaction({userId:user.id,role:user.role,requestId},async client=>(await client.query('SELECT rating,comments,created_at AS "createdAt",updated_at AS "updatedAt" FROM app.service_order_feedback WHERE service_order_id=$1',[id])).rows[0]??null); return ok(data,{requestId}); } catch(error){ return fail(error); } }
export async function POST(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { assertSameOrigin(request); const requestId=crypto.randomUUID(); const user=await requirePermission(request,requestId,"service.create"); const id=z.uuid().parse((await context.params).id); const body=await parseBody(request,input); const data=await withActorTransaction({userId:user.id,role:user.role,requestId},async client=>{ const order=(await client.query<{customerId:string;mechanicId:string|null;status:string}>('SELECT customer_id AS "customerId",assigned_mechanic_id AS "mechanicId",status FROM app.service_orders WHERE id=$1 FOR UPDATE',[id])).rows[0]; if(!order) throw new ApiError(404,"SERVICE_ORDER_NOT_FOUND","Service order tidak ditemukan"); if(order.status!=="completed"||!order.mechanicId) throw new ApiError(409,"FEEDBACK_NOT_READY","Rating hanya dapat dicatat setelah serah-terima selesai"); const row=(await client.query('INSERT INTO app.service_order_feedback(service_order_id,customer_id,mechanic_id,rating,comments,recorded_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(service_order_id) DO UPDATE SET rating=excluded.rating,comments=excluded.comments,recorded_by=excluded.recorded_by,updated_at=now() RETURNING rating,comments,updated_at AS "updatedAt"',[id,order.customerId,order.mechanicId,body.rating,body.comments??null,user.id])).rows[0]; await recordAudit(client,{actorId:user.id,requestId,action:"service_order.feedback.save",entityType:"service_order",entityId:id,after:row}); return row; }); return ok(data,{requestId}); } catch(error){ return fail(error); } }
