"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { AccessibleDialog } from "@/components/AccessibleDialog";

type Group = { category: string; amount: number };
type FinanceData = { range: { from: string; to: string }; summary: { totalIncome: number; totalCogs: number; operatingExpense: number; totalExpense: number; grossProfit: number; netProfit: number; grossMarginPercent: number; netMarginPercent: number; incomingCash: number; outgoingCash: number; receivables: number; payables: number; overduePayables: number }; trend: Array<{ date: string; income: number; expense: number; profit: number }>; incomeComposition: Group[]; expenseComposition: Group[]; payableVendors: Array<{ id: string; vendor: string; total: number; notDue: number; overdue: number; nearestDueAt?: string | null }>; activity: Array<{ kind: "income" | "expense" | "payable"; reference: string; counterparty: string; amount: number; occurred_at: string }> };
type Envelope<T> = { data: T; error?: { message?: string } | null };
const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" });
const numeric = new Intl.NumberFormat("id-ID", { notation: "compact", style: "currency", currency: "IDR", maximumFractionDigits: 1 });
const day = (value = new Date()) => value.toISOString().slice(0, 10);
const monthStart = () => { const value = new Date(); value.setDate(1); return day(value); };
async function request<T>(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await response.json() as Envelope<T>; if (!response.ok) throw new Error(body.error?.message || "Data keuangan belum dapat diproses"); return body.data; }

export function FinanceOverview({ role }: { role: string }) {
  const [from, setFrom] = useState(monthStart); const [to, setTo] = useState(() => day()); const [data, setData] = useState<FinanceData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [expenseOpen, setExpenseOpen] = useState(false); const [saving, setSaving] = useState(false);
  const canWrite = ["owner", "admin", "finance", "cashier"].includes(role);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await request<FinanceData>("/api/v1/intelligence/finance-overview?from=" + encodeURIComponent(from) + "&to=" + encodeURIComponent(to))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Dashboard keuangan belum dapat dimuat"); } finally { setLoading(false); } }, [from, to]);
  useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, [load]);
  async function submitExpense(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); try { await request("/api/v1/business/expenses", { method: "POST", body: JSON.stringify({ expenseNumber: "EXP-" + crypto.randomUUID().slice(0, 12).toUpperCase(), category: form.get("category"), description: form.get("description"), amount: Number(form.get("amount")), occurredAt: new Date(String(form.get("occurredAt"))).toISOString() }) }); setExpenseOpen(false); setMessage("Pengeluaran tersimpan dan profitabilitas diperbarui."); await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Pengeluaran gagal disimpan"); } finally { setSaving(false); } }
  const summary = data?.summary;
  return <section className="mx-auto max-w-7xl" aria-labelledby="finance-heading"><div className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-950 text-white shadow-xl"><div className="flex flex-col gap-5 px-5 py-6 sm:px-7 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-400">Finance & Profitability</p><h1 id="finance-heading" className="mt-2 text-2xl font-black sm:text-3xl">Visibilitas keuangan bengkel</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Pendapatan, HPP, pengeluaran, piutang, dan hutang vendor dari Service Order, penjualan, inventori, serta purchasing.</p></div><div className="grid gap-2 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-wide text-slate-300">Dari<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-white/15 bg-white/10 px-3 text-sm text-white" /></label><label className="text-xs font-bold uppercase tracking-wide text-slate-300">Sampai<input type="date" value={to} min={from} max={day()} onChange={(event) => setTo(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-white/15 bg-white/10 px-3 text-sm text-white" /></label></div></div><div className="flex flex-wrap gap-2 border-t border-white/10 px-5 py-3 sm:px-7"><button type="button" onClick={() => void load()} className="min-h-11 rounded-xl bg-white px-4 text-sm font-black text-slate-950">Muat ulang</button>{canWrite && <button type="button" onClick={() => setExpenseOpen(true)} className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-black text-white">Catat pengeluaran</button>}<Link href="/business/service-orders" className="inline-flex min-h-11 items-center rounded-xl border border-white/15 px-4 text-sm font-bold">Service Order</Link><Link href="/business/inventory" className="inline-flex min-h-11 items-center rounded-xl border border-white/15 px-4 text-sm font-bold">Inventori & HPP</Link><Link href="/business/vendors" className="inline-flex min-h-11 items-center rounded-xl border border-white/15 px-4 text-sm font-bold">Vendor</Link></div></div>
    {message && <p role="status" className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-bold text-blue-900">{message}</p>}
    {loading && <Loading />}{!loading && error && <div role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900"><p className="font-black">Dashboard belum dapat dimuat</p><p className="mt-1 text-sm">{error}</p><button onClick={() => void load()} className="mt-4 min-h-11 rounded-xl bg-red-700 px-4 text-sm font-bold text-white">Coba lagi</button></div>}
    {!loading && data && summary && <><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total pendapatan" value={money.format(summary.totalIncome)} helper="Service order dan penjualan" tone="bg-emerald-50 text-emerald-700" /><Metric label="Total biaya" value={money.format(summary.totalExpense)} helper="HPP dan operasional" tone="bg-red-50 text-red-700" /><Metric label="Gross profit" value={money.format(summary.grossProfit)} helper="Pendapatan dikurangi HPP" tone="bg-blue-50 text-blue-700" /><Metric label="Gross margin" value={summary.grossMarginPercent.toLocaleString("id-ID") + "%"} helper="Margin laba kotor" tone="bg-violet-50 text-violet-700" /><Metric label="Net profit" value={money.format(summary.netProfit)} helper="Setelah biaya operasional" tone="bg-amber-50 text-amber-700" /></div><div className="mt-5 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Panel title="Tren pendapatan, biaya, dan profit"><Trend points={data.trend} /></Panel><Panel title="Profitability summary"><Row label="Total revenue" value={money.format(summary.totalIncome)} /><Row label="Total HPP" value={money.format(summary.totalCogs)} /><Row label="Gross profit" value={money.format(summary.grossProfit)} accent /><Row label="Biaya operasional" value={money.format(summary.operatingExpense)} /><Row label="Net profit" value={money.format(summary.netProfit)} accent /><Row label="Net margin" value={summary.netMarginPercent.toLocaleString("id-ID") + "%"} /></Panel></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Composition title="Komposisi pendapatan" items={data.incomeComposition} tone="bg-emerald-500" /><Composition title="Komposisi biaya" items={data.expenseComposition} tone="bg-red-500" /></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Insight label="Kas masuk" value={money.format(summary.incomingCash)} helper="Pembayaran pelanggan" /><Insight label="Kas keluar vendor" value={money.format(summary.outgoingCash)} helper="Pembayaran hutang vendor" /><Insight label="Piutang pelanggan" value={money.format(summary.receivables)} helper="Invoice belum lunas" /><Insight label="Hutang jatuh tempo" value={money.format(summary.overduePayables)} helper={"Total hutang " + money.format(summary.payables)} danger={summary.overduePayables > 0} /></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Ringkasan payable vendor"><Payables rows={data.payableVendors} /></Panel><Panel title="Aktivitas keuangan terbaru"><ul className="divide-y divide-slate-100">{data.activity.map((item) => <li key={item.kind + item.reference} className="flex justify-between gap-3 py-3"><div><p className="font-bold text-slate-900">{item.counterparty}</p><p className="mt-1 text-xs text-slate-500">{item.reference} · {date.format(new Date(item.occurred_at))}</p></div><strong className={item.kind === "income" ? "text-emerald-700" : "text-red-700"}>{item.kind === "income" ? "+" : "-"}{numeric.format(item.amount)}</strong></li>)}</ul></Panel></div></>}
    {expenseOpen && <AccessibleDialog labelledBy="expense-title" onClose={() => setExpenseOpen(false)} showCloseButton panelClassName="max-w-lg"><form onSubmit={submitExpense} className="space-y-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-red-600">Operational expense</p><h2 id="expense-title" className="mt-1 text-2xl font-black">Catat pengeluaran</h2><p className="mt-1 text-sm text-slate-600">Data langsung masuk perhitungan net profit.</p></div><label className="block text-sm font-bold">Kategori<input name="category" required minLength={2} data-dialog-initial-focus className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3" placeholder="Operasional, listrik, transportasi" /></label><label className="block text-sm font-bold">Keterangan<textarea name="description" required minLength={2} className="mt-1 min-h-24 w-full rounded-xl border border-slate-300 p-3" /></label><label className="block text-sm font-bold">Jumlah<input name="amount" type="number" min="1" required className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3" /></label><label className="block text-sm font-bold">Waktu transaksi<input name="occurredAt" type="datetime-local" required defaultValue={new Date().toISOString().slice(0,16)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3" /></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setExpenseOpen(false)} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-bold">Batal</button><button disabled={saving} className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-black text-white disabled:opacity-50">{saving ? "Menyimpan..." : "Simpan pengeluaran"}</button></div></form></AccessibleDialog>}
  </section>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-slate-950">{title}</h2><div className="mt-4">{children}</div></section>; }
function Metric({ label, value, helper, tone }: { label: string; value: string; helper: string; tone: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={"inline-flex rounded-lg px-2.5 py-1 text-xs font-black uppercase tracking-wide " + tone}>{label}</span><p className="mt-3 text-2xl font-black tracking-tight text-slate-950">{value}</p><p className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-500">{helper}</p></article>; }
function Row({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="flex justify-between gap-4 border-b border-slate-100 py-3 last:border-0"><span className="text-sm text-slate-600">{label}</span><strong className={accent ? "text-emerald-700" : "text-slate-950"}>{value}</strong></div>; }
function Insight({ label, value, helper, danger = false }: { label: string; value: string; helper: string; danger?: boolean }) { return <article className={"rounded-2xl border p-5 shadow-sm " + (danger ? "border-red-200 bg-red-50" : "border-slate-200 bg-white")}><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className={"mt-2 text-xl font-black " + (danger ? "text-red-800" : "text-slate-950")}>{value}</p><p className="mt-2 text-xs text-slate-600">{helper}</p></article>; }
function Composition({ title, items, tone }: { title: string; items: Group[]; tone: string }) { const total = items.reduce((sum,item) => sum + item.amount, 0); return <Panel title={title}>{items.length ? <div className="space-y-4">{items.map((item) => { const percent = total ? item.amount / total * 100 : 0; return <div key={item.category}><div className="flex justify-between gap-3 text-sm"><span className="font-bold text-slate-800">{item.category}</span><span className="text-slate-600">{money.format(item.amount)} · {percent.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={"h-full rounded-full " + tone} style={{ width: Math.max(percent,2) + "%" }} /></div></div>; })}</div> : <p className="text-sm text-slate-500">Belum ada data pada periode ini.</p>}</Panel>; }
function Payables({ rows }: { rows: FinanceData["payableVendors"] }) { if (!rows.length) return <p className="text-sm text-slate-500">Tidak ada hutang vendor aktif.</p>; return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Vendor</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Belum tempo</th><th className="px-3 py-3">Jatuh tempo</th><th className="px-3 py-3">Tempo terdekat</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id}><td className="px-3 py-3 font-bold">{row.vendor}</td><td className="px-3 py-3">{money.format(row.total)}</td><td className="px-3 py-3">{money.format(row.notDue)}</td><td className="px-3 py-3 font-bold text-red-700">{money.format(row.overdue)}</td><td className="px-3 py-3">{row.nearestDueAt ? date.format(new Date(row.nearestDueAt)) : "—"}</td></tr>)}</tbody></table></div>; }
function Trend({ points }: { points: FinanceData["trend"] }) { const width = 760, height = 230, padding = 28, max = Math.max(1,...points.flatMap((item) => [item.income,item.expense,Math.max(item.profit,0)])); const path = (key: "income" | "expense" | "profit") => points.map((item,index) => { const x = padding + index * ((width-padding*2)/Math.max(points.length-1,1)); const y = height-padding-Math.max(item[key],0)/max*(height-padding*2); return x.toFixed(1) + "," + y.toFixed(1); }).join(" "); if (!points.length) return <p className="text-sm text-slate-500">Belum ada tren pada periode ini.</p>; return <div><div className="mb-3 flex flex-wrap gap-4 text-xs font-bold"><span className="text-emerald-700">● Pendapatan</span><span className="text-red-700">● Biaya</span><span className="text-blue-700">● Profit</span></div><svg viewBox={"0 0 " + width + " " + height} role="img" aria-label="Grafik tren pendapatan, biaya, dan profit" className="h-auto w-full"><path d={"M" + padding + " " + (height-padding) + "H" + (width-padding) + " M" + padding + " " + padding + "V" + (height-padding)} stroke="#cbd5e1" fill="none" /><polyline points={path("income")} fill="none" stroke="#059669" strokeWidth="4" strokeLinejoin="round" /><polyline points={path("expense")} fill="none" stroke="#dc2626" strokeWidth="4" strokeLinejoin="round" /><polyline points={path("profit")} fill="none" stroke="#2563eb" strokeWidth="4" strokeLinejoin="round" /></svg><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{date.format(new Date(points[0].date))}</span><span>{date.format(new Date(points[points.length-1].date))}</span></div></div>; }
function Loading() { return <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-busy="true">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-slate-100" />)}</div>; }
