-- Create the honda schema if it does not exist
CREATE SCHEMA IF NOT EXISTS honda;

-- Enable pg_trgm extension if not already enabled (for fast fuzzy search)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create the spareparts table inside the honda schema
CREATE TABLE IF NOT EXISTS honda.spareparts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code VARCHAR(100) NOT NULL,
    part_name TEXT NOT NULL,
    het NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for extremely fast searching (important for 45,000+ rows)
CREATE INDEX IF NOT EXISTS idx_spareparts_part_code ON honda.spareparts (part_code);
CREATE INDEX IF NOT EXISTS idx_spareparts_part_name_trgm ON honda.spareparts USING gin (part_name gin_trgm_ops);

-- Create a helper function for searching with multiple words (e.g. 'kampas beat')
CREATE OR REPLACE FUNCTION honda.search_spareparts(search_query text, motor_filter text DEFAULT '')
RETURNS SETOF honda.spareparts
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    query_parts text[];
    where_clause text := 'TRUE';
    i text;
BEGIN
    -- Split search query into array of words
    IF search_query IS NOT NULL AND trim(search_query) <> '' THEN
        query_parts := regexp_split_to_array(trim(search_query), '\s+');
        FOREACH i IN ARRAY query_parts LOOP
            where_clause := where_clause || ' AND (part_name ILIKE ' || quote_literal('%' || i || '%') || ' OR part_code ILIKE ' || quote_literal('%' || i || '%') || ')';
        END LOOP;
    END IF;

    -- Apply motor filter if provided
    IF motor_filter IS NOT NULL AND trim(motor_filter) <> '' THEN
        where_clause := where_clause || ' AND part_name ILIKE ' || quote_literal('%' || motor_filter || '%');
    END IF;

    RETURN QUERY EXECUTE '
        SELECT id, part_code, part_name, het, status, created_at
        FROM honda.spareparts
        WHERE ' || where_clause || '
        ORDER BY part_name ASC
        LIMIT 50;';
END;
$$;
