"use client";
import { FormEvent, useEffect, useState } from "react";

export function CustomerFeedbackPanel({ orderId }: { orderId: string }) {
  const [rating,setRating]=useState(5); const [comments,setComments]=useState(""); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{void fetch(`/api/v1/operations/service-orders/${orderId}/feedback`).then(async response=>{if(!response.ok)return;const body=await response.json();if(body.data){setRating(body.data.rating);setComments(body.data.comments??"");}});},[orderId]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");try{const response=await fetch(`/api/v1/operations/service-orders/${orderId}/feedback`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rating,comments:comments||null})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||"Rating gagal disimpan");setMessage("Rating pelanggan tersimpan.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Rating gagal disimpan");}finally{setSaving(false);}}
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><h2 className="text-base font-black">Rating pelanggan</h2><p className="mt-1 text-sm text-slate-600">Catat penilaian yang diberikan pelanggan setelah serah-terima.</p><form onSubmit={submit} className="mt-4 space-y-3"><label className="block text-sm font-bold">Nilai<select value={rating} onChange={event=>setRating(Number(event.target.value))} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3">{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label className="block text-sm font-bold">Catatan<textarea value={comments} onChange={event=>setComments(event.target.value)} maxLength={2000} className="mt-1 min-h-24 w-full rounded-xl border border-slate-300 p-3" /></label><button disabled={saving} className="min-h-11 rounded-xl bg-blue-800 px-4 text-sm font-black text-white disabled:opacity-50">{saving?"Menyimpan...":"Simpan rating"}</button>{message&&<p role="status" className="text-sm font-semibold text-slate-700">{message}</p>}</form></section>;
}
