import process from "node:process";

const baseUrl = process.env.E2E_BASE_URL || "http://127.0.0.1:37800";
const email = process.env.BOOTSTRAP_ADMIN_EMAIL || "admin@honda.local";
const password = process.env.BOOTSTRAP_ADMIN_PASSWORD;
if (!password) throw new Error("BOOTSTRAP_ADMIN_PASSWORD wajib diisi");
let cookie = "";

const anonymous = await fetch(`${baseUrl}/api/v1/catalog/products`);
if (anonymous.status !== 401) throw new Error("Anonymous access tidak ditolak");
const crossOriginLogin = await fetch(`${baseUrl}/api/v1/auth/login`, { method: "POST", headers: { "content-type": "application/json", origin: "https://attacker.invalid" }, body: JSON.stringify({ email, password }) });
if (crossOriginLogin.status !== 403) throw new Error("Cross-origin mutation tidak ditolak");

async function request(path, init = {}) {
  const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { "content-type": "application/json", origin: baseUrl, ...(cookie ? { cookie } : {}), ...init.headers } });
  const text = await response.text();
  const body = text ? JSON.parse(text) : null;
  if (!response.ok) throw new Error(`${init.method || "GET"} ${path}: ${response.status} ${body?.error?.message || text}`);
  return { response, body };
}

const health = await request("/api/health");
if (health.body.data.status !== "ok") throw new Error("Health gagal");
const login = await request("/api/v1/auth/login", { method: "POST", body: JSON.stringify({ email, password }) });
cookie = (login.response.headers.get("set-cookie") || "").split(";")[0];
if (!cookie) throw new Error("Session cookie tidak diterbitkan");
const suffix = Date.now().toString(36).toUpperCase();
const product = (await request("/api/v1/catalog/products", { method: "POST", body: JSON.stringify({ partCode: `E2E-${suffix}`, name: "Produk E2E", het: 10000, minimumStock: 2 }) })).body.data;
const injectionSearch = await request(`/api/v1/catalog/products?query=${encodeURIComponent("' OR 1=1 --")}`);
if (!Array.isArray(injectionSearch.body.data)) throw new Error("Search envelope invalid");
const customer = (await request("/api/v1/operations/customers", { method: "POST", body: JSON.stringify({ name: "Pelanggan E2E", phone: `08${Date.now().toString().slice(-10)}` }) })).body.data;
const models = (await request("/api/v1/catalog/models")).body.data;
const vehicle = (await request("/api/v1/operations/vehicles", { method: "POST", body: JSON.stringify({ customerId: customer.id, vehicleModelId: models[0]?.id || null, plateNumber: `E2E${suffix.slice(-5)}`, odometer: 1200 }) })).body.data;
const order = (await request("/api/v1/operations/service-orders", { method: "POST", body: JSON.stringify({ orderNumber: `SO-${suffix}`, customerId: customer.id, vehicleId: vehicle.id, complaint: "Pengujian workflow E2E" }) })).body.data;
await request(`/api/v1/operations/service-orders/${order.id}/details`, { method: "POST", body: JSON.stringify({ action: "job", name: "Servis E2E", price: 50000 }) });
await request(`/api/v1/operations/service-orders/${order.id}/status`, { method: "PATCH", body: JSON.stringify({ status: "in_progress" }) });
await request(`/api/v1/operations/service-orders/${order.id}/status`, { method: "PATCH", body: JSON.stringify({ status: "quality_check" }) });
const profile = await request(`/api/v1/operations/customers/${customer.id}/profile`);
if (profile.body.data.orders[0]?.id !== order.id) throw new Error("Service history tidak terhubung");
if (process.env.SERVICE_RECEPTION_E2E_ENABLED === "true") {
  const receptionPhone = `0818${Date.now().toString().slice(-8)}`;
  const receptionSuffix = `${suffix}R`;
  const receptionBase = "/api/v1/operations/service-reception";
  const receptionCustomer = (await request(`${receptionBase}/customers`, { method: "POST", body: JSON.stringify({ name: `Pelanggan Reception ${receptionSuffix}`, phone: receptionPhone }) })).body.data;
  const duplicateCustomer = await fetch(`${baseUrl}${receptionBase}/customers`, { method: "POST", headers: { "content-type": "application/json", origin: baseUrl, cookie }, body: JSON.stringify({ name: `Duplikat ${receptionSuffix}`, phone: receptionPhone }) });
  if (duplicateCustomer.status !== 409) throw new Error(`Duplikat customer reception tidak ditolak: ${duplicateCustomer.status}`);
  const receptionVehicle = (await request(`${receptionBase}/vehicles`, { method: "POST", body: JSON.stringify({ customerId: receptionCustomer.id, plateNumber: `REC${receptionSuffix.slice(-6)}`, odometer: 25000 }) })).body.data;
  const duplicateVehicle = await fetch(`${baseUrl}${receptionBase}/vehicles`, { method: "POST", headers: { "content-type": "application/json", origin: baseUrl, cookie }, body: JSON.stringify({ customerId: receptionCustomer.id, plateNumber: receptionVehicle.plateNumber.toLowerCase(), odometer: 25000 }) });
  if (duplicateVehicle.status !== 409) throw new Error(`Duplikat plat reception tidak ditolak: ${duplicateVehicle.status}`);
  const searched = (await request(`${receptionBase}/search?query=${encodeURIComponent(receptionVehicle.plateNumber.replaceAll("-", ""))}`)).body.data;
  if (!searched.some((item) => item.id === receptionCustomer.id && item.vehicles?.some((vehicle) => vehicle.id === receptionVehicle.id))) throw new Error("Search reception tidak menemukan kendaraan milik pelanggan");
  const receptionPayload = { customerId: receptionCustomer.id, vehicleId: receptionVehicle.id, serviceType: "routine", complaint: "Pemeriksaan reception E2E", odometer: 25100, checklist: { fuelLevel: 50, physicalCondition: "Kondisi normal", belongings: ["Helm"], notes: "E2E" }, idempotencyKey: `reception-order-${receptionSuffix}` };
  const receptionOrder = (await request(`${receptionBase}/orders`, { method: "POST", body: JSON.stringify(receptionPayload) })).body.data;
  const replayedReceptionOrder = (await request(`${receptionBase}/orders`, { method: "POST", body: JSON.stringify(receptionPayload) })).body.data;
  if (receptionOrder.id !== replayedReceptionOrder.id || receptionOrder.status !== "open") throw new Error("Atomic order atau idempotency reception gagal");
}
const vendor = (await request("/api/v1/business/vendors", { method: "POST", body: JSON.stringify({ code: `V-${suffix}`, name: "Vendor E2E" }) })).body.data;
const purchaseOrder = (await request("/api/v1/business/purchase-orders", { method: "POST", body: JSON.stringify({ orderNumber: `PO-${suffix}`, vendorId: vendor.id, items: [{ productId: product.id, quantity: 5, unitPrice: 7000 }] }) })).body.data;
await request(`/api/v1/business/purchase-orders/${purchaseOrder.id}/status`, { method: "PATCH", body: JSON.stringify({ status: "submitted" }) });
await request(`/api/v1/business/purchase-orders/${purchaseOrder.id}/status`, { method: "PATCH", body: JSON.stringify({ status: "approved" }) });
const warehouses = (await request("/api/v1/operations/warehouses")).body.data;
const receiptPayload = { receiptNumber: `GR-${suffix}`, purchaseOrderId: purchaseOrder.id, warehouseId: warehouses[0].id, idempotencyKey: `receipt-${suffix}`, items: [{ purchaseOrderItemId: purchaseOrder.items[0].id, quantity: 5, unitCost: 7000 }] };
const receipt = (await request("/api/v1/business/receipts", { method: "POST", body: JSON.stringify(receiptPayload) })).body.data;
const replayedReceipt = (await request("/api/v1/business/receipts", { method: "POST", body: JSON.stringify(receiptPayload) })).body.data;
if (receipt.id !== replayedReceipt.id) throw new Error("Idempotency receipt gagal");
const reservedPart = (await request(`/api/v1/operations/service-orders/${order.id}/details`, { method: "POST", body: JSON.stringify({ action: "reserve_part", warehouseId: warehouses[0].id, productId: product.id, quantity: 1, unitPrice: 10000, unitCost: 7000 }) })).body.data;
await request(`/api/v1/operations/service-orders/${order.id}/details`, { method: "POST", body: JSON.stringify({ action: "consume_part", partId: reservedPart.id, idempotencyKey: `service-usage-${suffix}` }) });
await request("/api/v1/business/customer-invoices", { method: "POST", body: JSON.stringify({ invoiceNumber: `CI-${suffix}`, serviceOrderId: order.id, discount: 0, tax: 0 }) });
const vendorInvoice = (await request("/api/v1/business/vendor-invoices", { method: "POST", body: JSON.stringify({ invoiceNumber: `VI-${suffix}`, vendorId: vendor.id, purchaseOrderId: purchaseOrder.id, total: 35000, issuedAt: "2026-09-27" }) })).body.data;
await request("/api/v1/business/payments", { method: "POST", body: JSON.stringify({ paymentNumber: `PAY-${suffix}`, direction: "outgoing", vendorInvoiceId: vendorInvoice.id, amount: 35000, method: "transfer", idempotencyKey: `payment-${suffix}` }) });
await request("/api/v1/intelligence/follow-ups", { method: "POST", body: JSON.stringify({ customerId: customer.id, serviceOrderId: order.id, dueAt: "2026-10-01T08:00:00.000Z", channel: "whatsapp" }) });
await request("/api/v1/intelligence/reminders", { method: "POST", body: JSON.stringify({ customerId: customer.id, vehicleId: vehicle.id, dueAt: "2026-10-01T08:00:00.000Z" }) });
const dashboard = await request("/api/v1/intelligence/dashboard");
const metrics = await request("/api/v1/intelligence/metrics");
const exported = await fetch(`${baseUrl}/api/v1/intelligence/export`, { headers: { cookie } });
if (!dashboard.body.data || !metrics.body.data || !exported.ok || metrics.body.data.monthlyCogs < 7000 || metrics.body.data.monthlyGrossProfit <= 0) throw new Error("Reporting E2E gagal");
const registers = (await request("/api/v1/pos/registers")).body.data;
const posProducts = (await request(`/api/v1/pos/products?registerId=${registers[0].id}&query=${encodeURIComponent(product.partCode)}`)).body.data;
const posProduct = posProducts.find((item) => item.id === product.id);
if (!posProduct || posProduct.hpp !== undefined || Number(posProduct.availableQuantity) < 1) throw new Error("POS product contract atau stok gagal");
const posPayload = { registerId: registers[0].id, items: [{ productId: product.id, quantity: "1", discount: "0" }], payments: [{ method: "cash", amount: "10000.00", idempotencyKey: `pos-payment-${suffix}` }], tax: "0", idempotencyKey: `pos-checkout-${suffix}` };
const sale = (await request("/api/v1/pos/checkout", { method: "POST", body: JSON.stringify(posPayload) })).body.data;
const replayedSale = (await request("/api/v1/pos/checkout", { method: "POST", body: JSON.stringify(posPayload) })).body.data;
if (!sale.id || replayedSale.id !== sale.id) throw new Error("Idempotency checkout POS gagal");
const saleDetail = (await request(`/api/v1/pos/sales/${sale.id}`)).body.data;
const posReceipt = (await request(`/api/v1/pos/sales/${sale.id}/receipt`)).body.data;
if (!saleDetail.items?.some((item) => item.productId === product.id) || posReceipt.saleNumber !== sale.saleNumber) throw new Error("Receipt POS tidak konsisten");
const voidedSale = (await request(`/api/v1/pos/sales/${sale.id}/void`, { method: "POST", body: JSON.stringify({ reason: "Pembersihan E2E POS" }) })).body.data;
if (voidedSale.status !== "voided") throw new Error("Void sale POS gagal");
if (process.env.POS_OPEN_BILL_E2E_ENABLED === "true") {
  const serviceCatalog = (await request("/api/v1/pos/services")).body.data;
  if (!Array.isArray(serviceCatalog) || !serviceCatalog[0]?.id || !serviceCatalog[0]?.fixedPrice) throw new Error("Katalog jasa POS invalid");
  const openBillCustomer = (await request("/api/v1/operations/customers", { method: "POST", body: JSON.stringify({ name: `Open Bill E2E ${suffix}`, phone: `089${Date.now().toString().slice(-9)}` }) })).body.data;
  const stockBeforeSave = Number((await request(`/api/v1/pos/products?registerId=${registers[0].id}&query=${encodeURIComponent(product.partCode)}`)).body.data.find((item) => item.id === product.id)?.availableQuantity);
  const openBillPayload = { customerId: openBillCustomer.id, registerId: registers[0].id, items: [{ productId: product.id, quantity: "1", discount: "0" }, { serviceId: serviceCatalog[0].id, quantity: "1", discount: "0" }] };
  const openBill = (await request("/api/v1/pos/open-bills", { method: "PUT", body: JSON.stringify(openBillPayload) })).body.data;
  const restoredOpenBill = (await request(`/api/v1/pos/open-bills?customerId=${openBillCustomer.id}`)).body.data;
  const stockAfterSave = Number((await request(`/api/v1/pos/products?registerId=${registers[0].id}&query=${encodeURIComponent(product.partCode)}`)).body.data.find((item) => item.id === product.id)?.availableQuantity);
  if (restoredOpenBill?.id !== openBill.id || stockBeforeSave !== stockAfterSave) throw new Error("Restore atau non-reservation Open Bill gagal");
  const openBillCheckout = { registerId: registers[0].id, customerId: openBillCustomer.id, openBillId: openBill.id, items: openBillPayload.items, payments: [{ method: "cash", amount: "1000000.00", idempotencyKey: `open-bill-payment-${suffix}` }], tax: "0", idempotencyKey: `open-bill-checkout-${suffix}` };
  const openBillSale = (await request("/api/v1/pos/checkout", { method: "POST", body: JSON.stringify(openBillCheckout) })).body.data;
  const openBillReplay = (await request("/api/v1/pos/checkout", { method: "POST", body: JSON.stringify(openBillCheckout) })).body.data;
  const stockAfterCheckout = Number((await request(`/api/v1/pos/products?registerId=${registers[0].id}&query=${encodeURIComponent(product.partCode)}`)).body.data.find((item) => item.id === product.id)?.availableQuantity);
  if (openBillReplay.id !== openBillSale.id || stockAfterCheckout !== stockBeforeSave - 1) throw new Error("Idempotency atau stok checkout Open Bill gagal");
}
const audit = await request("/api/v1/audit");
if (!audit.body.data.some((event) => event.entityId === product.id)) throw new Error("Audit product tidak ditemukan");
await request("/api/v1/auth/logout", { method: "POST", body: "{}" });
const revokedSession = await fetch(`${baseUrl}/api/v1/auth/me`, { headers: { cookie } });
if (revokedSession.status !== 401) throw new Error("Session revoke gagal");
console.log(JSON.stringify({ verified: true, productId: product.id, customerId: customer.id, serviceOrderId: order.id }));
