import crypto from "node:crypto";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/server/auth/permissions";
import { withActorTransaction } from "@/server/db";
import { ApiError, assertSameOrigin, fail, ok, parseBody } from "@/server/http";
const input=z.object({orderNumber:z.string().trim().min(3).max(80),customerId:z.uuid(),vehicleId:z.uuid(),complaint:z.string().trim().min(2).max(2000),odometer:z.coerce.number().min(0).optional(),assignedMechanicId:z.uuid().nullable().optional()});
export async function GET(request:NextRequest){try{const requestId=crypto.randomUUID();const user=await requirePermission(request,requestId,"service.read");const data=await withActorTransaction({userId:user.id,role:user.role,requestId},async(c)=>(await c.query("SELECT s.id,s.order_number AS \"orderNumber\",s.status,s.complaint,s.opened_at AS \"openedAt\",c.name AS \"customerName\",v.plate_number AS \"plateNumber\" FROM app.service_orders s JOIN app.customers c ON c.id=s.customer_id JOIN app.customer_vehicles v ON v.id=s.vehicle_id ORDER BY s.created_at DESC LIMIT 100")).rows);return ok(data,{requestId});}catch(error){return fail(error);}}
export async function POST(request:NextRequest){try{assertSameOrigin(request);const requestId=crypto.randomUUID();const user=await requirePermission(request,requestId,"service.create");const body=await parseBody(request,input);const data=await withActorTransaction({userId:user.id,role:user.role,requestId},async(c)=>{const vehicle=(await c.query("SELECT 1 FROM app.customer_vehicles WHERE id=$1 AND customer_id=$2",[body.vehicleId,body.customerId])).rows[0];if(!vehicle)throw new ApiError(422,"VEHICLE_CUSTOMER_MISMATCH","Kendaraan tidak terdaftar untuk pelanggan ini");const row=(await c.query("INSERT INTO app.service_orders(order_number,customer_id,vehicle_id,assigned_mechanic_id,status,complaint,odometer,opened_at,created_by,updated_by) VALUES($1,$2,$3,$4,'open',$5,$6,now(),$7,$7) RETURNING id,order_number AS \"orderNumber\",status",[body.orderNumber,body.customerId,body.vehicleId,body.assignedMechanicId||null,body.complaint,body.odometer||null,user.id])).rows[0];await c.query("INSERT INTO app.service_order_status_history(service_order_id,to_status,reason,actor_id) VALUES($1,'open','Order dibuka',$2)",[row.id,user.id]);return row;});return ok(data,{requestId});}catch(error){return fail(error);}}
